### ISSUE TITLE
Covariates

### ISSUE THREAD

**Issue by sarah-chapin** [ManchesterBioinference/GPcounts#14]
I am using GPCounts to analyze spatial single-cell RNAseq data, and I would like to include a categorical covariate. Do you have any recommendations about where to incorporate a covariate in the GPCounts analysis?

**Comment by magnusrattray** [comment]
You can include covariates using extra dimensions of your inputs. For categorical variables perhaps you can use a one-hot encoding and standard squared exponential kernel so that distances are the same between all categories? We have not tried this but it should be possible within the general GPflow framework.

**Comment by magnusrattray** [comment]
There's a GPflow slack which may be helpful if you have questions about how to do this in GPflow. GPcounts is just some new likelihoods sitting on top of GPflow so most things you can do in GPflow you can also do in GPcounts in order to use our NB likelihood.

**Comment by sarah-chapin** [comment]
Thank you, this is very helpful. I will try implementing one-hot encoding within GPFflow.

**Comment by NuhaSaud** [comment]
Hi @sarah-chapin, we would be happy to have a look at it if you have some test data we could look at it.

**Comment by sarah-chapin** [comment]
Hi @NuhaSaud, that would be great! Do you have an email address where I can send the data?

**Comment by sokratiag** [comment]
Hi sarah-chapin,

Can you please send the test data in sokratia.georgaka@manchester.ac.uk? What kind of spatial single-cell data is this? I mean is it visium/slide-seq etc?

**Comment by NuhaSaud** [comment]
Yes, send the data to this email n_altayash@hotmail.com, please.
