### ISSUE TITLE
Chi2 test in Model_selection_test()

### ISSUE THREAD

**Issue by lijing-lin** [ManchesterBioinference/GPcounts#5]
In computing pvalue, should `results['p_value'] = 1 - ss.chi2.cdf(results['log_likelihood_ratio'], df=1)` be `results['p_value'] = 1 - ss.chi2.cdf(2 * results['log_likelihood_ratio'], df=1)` ?

**Comment by sokratiag** [comment]
Hi Lijing, 

Why 2*results?

**Comment by lijing-lin** [comment]
Assuming this is likelihood ratio chi-squared test, the test statistics will be -2*(log_likelihood(model1) - log_likelihood(model0))?

**Comment by sokratiag** [comment]
Yes lijing, you are right - we will change it accordingly. Thanks a lot for spotting this!
